preset: laravel

enabled:
  - concat_with_spaces

disabled:
  - concat_without_spaces
  - function_declaration
  - not_operator_with_successor_space
  - laravel_phpdoc_alignment
  - laravel_phpdoc_separation

