preset: laravel

enabled:
  - concat_with_spaces
  - alpha_ordered_imports

disabled:
  - concat_without_spaces
  - function_declaration
  - not_operator_with_successor_space
  - length_ordered_imports

